language: python
python:
  - "2.6"
  - "2.7"
install: pip install -r requirements.txt --use-mirrors
before_script:
  - mkdir -p vendors
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip -nv
  - unzip -qd vendors google_appengine_1.8.8.zip
script: ./.travis-runner.py
notifications:
  email:
    - d-eve-lopment@googlegroups.com
